source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
use_frameworks!

def swinject_pods
    pod 'Swinject'
    pod 'SwinjectStoryboard'
end

target 'EventsApp' do
    swinject_pods
end

target 'EventsAppTests' do
    swinject_pods
end


